### ISSUE TITLE
Path type on routes

### ISSUE THREAD

**Issue by Garito** [channelcat/sanic#537] opened 2017-03-09 17:44 UTC
Hi!
Looking for something equivalent to the flask's path type of segment on routes
Something like:
/my/fixed/path/<path:path>/the/<rest>/of/the/url
where if you ask for /my/fixed/path/this/will/be/part/of/path/the/thiswillberest/of/the/url
path will be /this/will/be/part/of/path
rest will be thiswillberest

Any ideas?

Thank

**Comment by r0fls** [comment] 2017-05-09 08:27
I don't fully understand. Can you point to a flask example or a give a more precise explanation? Ideally code or pseudocode explaining what feature you're describing would be helpful.

**Comment by messense** [comment] 2017-05-09 08:29
You want this https://github.com/channelcat/sanic/pull/632?

**Comment by r0fls** [comment] 2017-08-21 07:34
I'm closing this since we haven't gotten a response. Please feel free to reopen if the issue is not addressed.

**Closed by r0fls** 2017-08-21 07:34 UTC
