### ISSUE TITLE
Issue replicating websocket example

### ISSUE THREAD

**Issue by Sniedes722** [channelcat/sanic#648] opened 2017-04-17 08:15 UTC
When trying to replicate the websocket example, keep getting the same issue:
```terminal
2017-04-17 08:10:35,759: INFO: Goin' Fast @ http://0.0.0.0:8080
2017-04-17 08:10:35,774: INFO: Starting worker [8146]
2017-04-17 08:10:35,774: INFO: Starting worker [8145]
2017-04-17 08:10:42,336: ERROR: Traceback (most recent call last):
  File "/home/ubuntu/workspace/.venv/lib/python3.5/site-packages/websockets/handshake.py", line 85, in check_request
    assert get_header('Upgrade').lower() == 'websocket'
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/workspace/.venv/lib/python3.5/site-packages/sanic/websocket.py", line 52, in websocket_handshake
    key = handshake.check_request(get_header)
  File "/home/ubuntu/workspace/.venv/lib/python3.5/site-packages/websockets/handshake.py", line 93, in check_request
    raise InvalidHandshake("Invalid request") from exc
websockets.exceptions.InvalidHandshake: Invalid request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/workspace/.venv/lib/python3.5/site-packages/sanic/app.py", line 465, in handle_request
    response = await response
  File "/home/ubuntu/workspace/.venv/lib/python3.5/site-packages/sanic/app.py", line 205, in websocket_handler
    ws = await protocol.websocket_handshake(request)
  File "/home/ubuntu/workspace/.venv/lib/python3.5/site-packages/sanic/websocket.py", line 55, in websocket_handshake
    raise InvalidUsage('Invalid websocket request')
sanic.exceptions.InvalidUsage: Invalid websocket request
```

**Comment by r0fls** [comment] 2017-04-24 07:33
I can't reproduce this. What version are you using?

**Comment by Sniedes722** [comment] 2017-04-24 07:40
@r0fls this was a docker container running 16.04.

**Comment by r0fls** [comment] 2017-04-24 07:41
Was it the latest sanic version? I'm using 0.5.1.

**Comment by Zheaoli** [comment] 2017-04-26 07:44
@r0fls I reproduce this situation,
I guess he use the Nginx or other server software as a request proxy tool, but he don't set the right option.

@Sniedes722 

For example , In Nginx, if you want use it to proxy a websocket request, you must set proxy option like this:
~~~Conf
server {
    listen 8020;
    location / {
        proxy_pass http://websocket;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}
~~~ 

if you don't do that, the request header will just like this:
![image](https://cloud.githubusercontent.com/assets/7054676/25423369/01527834-2a97-11e7-9ee1-3747cfc23526.png)

but the right header is like this:

![image](https://cloud.githubusercontent.com/assets/7054676/25423432/3f1cc944-2a97-11e7-8305-b22f5f05801a.png)

So I guess it's not the Sanic error.

**Comment by r0fls** [comment] 2017-04-27 06:07
Closing via @Zheaoli's comment. @Sniedes722 feel free to reopen if that solution doesn't work for you or you need more help.

**Closed by r0fls** 2017-04-27 06:07 UTC
Labels: needs investigation
