### ISSUE TITLE
python3.5.2 visite is ok but console return error

### ISSUE THREAD

**Issue by yxlwfds** [channelcat/sanic#642] opened 2017-04-16 13:58 UTC
2017-04-16 20:54:32,081: ERROR: Traceback (most recent call last):
  File "httptools/parser/parser.pyx", line 270, in httptools.parser.parser.cb_on_headers_complete (httptools/parser/parser.c:4402)
  File "httptools/parser/parser.pyx", line 123, in httptools.parser.parser.HttpParser._on_headers_complete (httptools/parser/parser.c:2079)
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 165, in on_headers_complete
    transport=self.transport
  File "/usr/local/lib/python3.5/dist-packages/sanic/request.py", line 46, in __init__
    self._parsed_url = parse_url(url_bytes)
  File "httptools/parser/parser.pyx", line 446, in httptools.parser.parser.parse_url (httptools/parser/parser.c:6981)
httptools.parser.errors.HttpParserInvalidURLError: invalid url b'check.proxyradar.com:80'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 144, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserCallbackError: the on_headers_complete callback failed

2017-04-16 21:41:01,901: ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 456, in handle_request
    handler, args, kwargs = self.router.get(request)
  File "/usr/local/lib/python3.5/dist-packages/sanic/router.py", line 288, in get
    return self._get(request.path, request.method, '')
  File "/usr/local/lib/python3.5/dist-packages/sanic/router.py", line 337, in _get
    raise NotFound('Requested URL {} not found'.format(url))
sanic.exceptions.NotFound: Requested URL /setup.cgi not found

2017-04-16 21:53:25,037: ERROR: NoneType

**Comment by r0fls** [comment] 2017-04-17 03:46
Please include a minimal example to reproduce this.

**Comment by seemethere** [comment] 2017-04-24 19:18
Closing due to no example provided.

**Closed by seemethere** 2017-04-24 19:18 UTC
