### ISSUE TITLE
Error: Bad Request, all HTTP requests being responded with 400

### ISSUE THREAD

**Issue by Izacht13** [channelcat/sanic#247] opened 2016-12-28 22:54 UTC
It has been at least 2 weeks that I have been trying to solve this issue, I've cleared my browser cookies and cache, I've delved deep into both sanic and httptools sources.

My code is simply:
```py
import sanic

app = sanic.Sanic(__name__)

@app.route("/")
async def index(request):
    return sanic.response.text("Hello World")

app.run(port=8080, debug=True)
```

Which works in my "test.py" file, but not in my main python file.

I use FireFox primarily (The issue is the same in Chrome), and this is the HTTP request it's sending:
```http
Host: localhost:8080
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
Accept: text/html,application/json,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Cache-Control: max-age=0
```

Noticed I tried adding "application/json" to the default Accept header, which did nothing.

I can't tell if sanic is eating an error, which is what I first though it was when the code was more complex.

Like I said, this same code works in a different file, but it couldn't possible have anything to do with the file name itself, could it?

EDIT: I tried deleting \_\_pycache\_\_ from the executing directory entirely, it didn't seem to have any effect. I also should mention that this issue seems to come and go, ill edit the code a little bit and the issue will go away, but only for a time. Then it comes back and I'm left trying to debug it for days, then it will go away magically.

**Comment by seemethere** [comment] 2016-12-29 00:02
Yeah I cannot reproduce on my machine, could you share some more details of your machine?

**Comment by Izacht13** [comment] 2016-12-29 03:38
I'm running Arch Linux ( *The only distro :P* ) with Gnome Shell ( *Gnome 3* ) as my desktop. Visual Studio Code is my current workspace.

**Comment by Izacht13** [comment] 2016-12-29 03:44
And now for some reason its working again... Ugh, this is so strange.

**Comment by seemethere** [comment] 2016-12-30 16:52
Yeah i'm going to have to guess it's something to do with the port and another application using the same port. A lot of other applications, to my knowledge, also use port 8080 for things.

Going to close this for now but feel free to reopen if this resurfaces.

**Closed by seemethere** 2016-12-30 16:52 UTC
