### ISSUE TITLE
Serve static directory

### ISSUE THREAD

**Issue by faviouz** [channelcat/sanic#374] opened 2017-01-30 16:19 UTC
I have a small application with the following directory hierarchy:

```
$ tree
.
├── client
│   ├── index.html
│   └── package.json
└── server
    ├── api.py
    └── requirements.txt

2 directories, 4 files
```

From `api.py` I want to serve the `client/` directory to the `/` route (while avoiding moving the `client/` directory inside `server/`). Something like this should work:

```
app.static('/', os.path.abspath('../client'))
```

However when I try to hit the route I just get:

```
sanic.exceptions.NotFound: Requested URL / not found
```

Any ideas?

**Comment by faviouz** [comment] 2017-01-30 16:32
On a closer look, the issue does not seem to lie within the fact that `client/` is outside the working directory of `app.py`. Just for the sake of an example, I've moved `client/` inside `server/`.

```
$ tree
.
└── server
    ├── api.py
    ├── client
    │   ├── index.html
    │   └── package.json
    └── requirements.txt

2 directories, 4 files
```

[Following the documentation](https://sanic.readthedocs.io/en/latest/sanic/static_files.html), I can't seem to serve a directory at all.

```
app.static('/', './client')
```

Still having the same issue. What's up with that? Am I doing something wrong?

**Comment by faviouz** [comment] 2017-01-30 16:38
Serving individual files works fine though.

```
 app.static('/', '../client/index.html')
```

**Comment by r0fls** [comment] 2017-02-01 02:00
@faviouz I can't reproduce this. Are you looking for a directory listing? When I use the following example I can access the files in the current directory:

```python
from sanic import Sanic
from sanic.response import text

app = Sanic()

@app.route('/')
def handler(request):
    return text(request.url)

app.static('/static', './')

app.run(debug=True)
```

**Comment by seemethere** [comment] 2017-02-01 14:00
I think he's saying he want's to specify a directory to serve at the root route `/` without having to move all the files to the current directory.

**Comment by seemethere** [comment] 2017-02-01 14:09
Per the test code we use to test serving static files (slightly modified to fit your scenario):

```python
from sanic import Sanic

current_directory = os.path.dirname(os.path.abspath(current_file))
static_directory = os.path.join(current_directory, 'client')

app.static('', static_directory)

app.run(debug=True)
```

**Comment by seemethere** [comment] 2017-02-03 00:05
Closing will reopen if necessary.

**Closed by seemethere** 2017-02-03 00:05 UTC
Labels: bug

**Comment by yingshaoxo** [comment] 2020-06-03 16:22
To be more clear, if you want to let sanic work with other front-end frameworks like reactjs or vuejs, you should use the following codes:

```
from sanic import Sanic, response

app = Sanic(name="front-end app")

dist_directory = './dist'
app.static('/', dist_directory)

@app.route("/")
async def index(request):
    return await response.file(dist_directory + "/index.html")

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8888, debug=True)
```

or just:

```
app.static('/', './build/index.html')
app.static('/', './build')
```

**Comment by pmgexpo17** [comment] 2021-11-16 02:28
Posting this solution (tested .. it works) for anyone who has issues serving simple static files
My project is for websocket comms between a browser and embedded server
For non-socketio apps just remove the related lines
`
import os
import socketio
from sanic import Sanic

currDir = os.path.dirname(os.path.realpath(__file__))
app = Sanic(__name__)
app.static("/",f"{currDir}/public/index.html")
sio = socketio.AsyncServer()
sio.attach(app)

if __name__ == '__main__':
    app.run("127.0.0.1",5000)
`

**Comment by ahopkins** [comment] 2021-11-16 08:08
>  For non-socketio apps just remove the related lines

If you are _only_ serving static files:

```bash
$ sanic /path/to/some/dir --simple
```
