### ISSUE TITLE
How to response 204 using response.json() 

### ISSUE THREAD

**Issue by alaminopu** [channelcat/sanic#1102] opened 2018-01-28 08:53 UTC
Usually the `DELETE` request should return a [204](https://httpstatuses.com/204) response. How can I send 204 response using sanic. I was trying something like below. 

```python
return response.json(
        None,
        status=204
    )
```

But it doesn't work, it response with null.

**Comment by ahopkins** [comment] 2018-01-28 22:36
That looks right to me. Can you post the raw response. Are you sure you are not getting the right status code? I do something similar, albeit with `response.text`

    text('', status=204)

Works just fine.

**Comment by alaminopu** [comment] 2018-01-31 06:04
If I use `response.text()` it's working fine. Why can't get the same response using `response .json()`? 

The following response with 204 but with `""` string in the response body.  For 204 response, content-length should be 0. 

```python
return response.json(
       '',
        status=204
    )
```

**Comment by ahopkins** [comment] 2018-01-31 07:34
Try this:

    return response.json(None, status=204)

**Comment by alaminopu** [comment] 2018-01-31 07:55
As I mentioned in my first comment. the following doesn't work. 

```python
return response.json(None, status=204)
```

It return a response with 204 but with `null` in the response body

**Comment by r0fls** [comment] 2018-01-31 22:42
@alaminopu are you using a `delete` route? With the below example, I do get a 0 length response:

```python
from sanic import Sanic
from sanic.response import json

app = Sanic()

@app.delete("/")
async def test(request):
    return json(None, status=204)

if __name__ == "__main__":
    app.run(host="localhost", port=8010)
```

```
$ curl -s -XDELETE localhost:8010 | wc -l
0
```

However, the `Content-Length` header is incorrect.

```
 curl -v -XDELETE localhost:8010
* Rebuilt URL to: localhost:8010/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8010 (#0)
> DELETE / HTTP/1.1
> Host: localhost:8010
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 204 No Content
< Connection: keep-alive
< Keep-Alive: 5
< Content-Length: 4
< Content-Type: application/json
< 
* Excess found in a non pipelined read: excess = 4 url = / (zero-length body)
* Connection #0 to host localhost left intact
```

**Comment by arnulfojr** [comment] 2018-02-01 10:37
@alaminopu @ahopkins @r0fls This is happening because the `json_dumps` functions try to deserialize `None` which returns `'null'` as a string, making this a response length of `4` even tho the HTTP code is 204 with no content, as I can see (maybe I'm incorrect) Sanic indeed returns `'null'`.
So, technically returning `None` is correct as returns `null`, when you use the 204 code then tecnically there's no body (you can read this [RFC for HTTP/1.1](https://tools.ietf.org/html/rfc2616#section-10.2.5)) this means the according to the specification:
> The 204 response MUST NOT include a message-body, and thus is always
   terminated by the first empty line after the header fields.
therefore the Header is proper, but the body is cut off.

I would propose to have a `None` response to have `''` (empty string) as no content, instead of `null` (for all response codes)

What you think?

**Comment by h-wei** [comment] 2018-02-01 23:35
try this:
```return response.json({}, 204}```

**Comment by h-wei** [comment] 2018-02-01 23:55
@r0fls It is NOT a bug.  The status code 204 shows 'no content'.  It means we check status code first and ignore check it's content.
@alaminopu @abhishek7 `json.dumps(None)` and `json.dumps('')` isn't normal usage. consider this explicit statement `json.dumps({})`

**Comment by r0fls** [comment] 2018-02-02 01:32
@h-wei the fact that the content-length and the actual body length differ is a bug. Please see [RFC 2616](https://tools.ietf.org/html/rfc2616) and refrain from YELLING:

>When a Content-Length is given in a message where a message-body is allowed, its field value MUST exactly match the number of OCTETs in the message-body.

**Comment by r0fls** [comment] 2018-02-02 21:21
closing per #1113

**Closed by r0fls** 2018-02-02 21:21 UTC
Labels: bug
