### ISSUE TITLE
[question] How to pass data from meddleware to route withou using decorator

### ISSUE THREAD

**Issue by eisneim** [channelcat/sanic#974] opened 2017-10-15 12:42 UTC
since there is no context object and request object can not be modified, so how can i pass data from middleware to route function? assign data in request.args is not secure.

thanks for any suggestion

**Comment by ashleysommer** [comment] 2017-10-15 23:32
This is a great question.

There is no _proper_ way to do it at the moment.
I have a plugin where I need to pass a message from a Request middleware to a corresponding Response middleware. That is very difficult and similar to your question.

They way I do it, is to add an entry in the request headers dict:
```
# set a const for your variable
MY_MIDDLEWARE_VAR = "x-my-middlware-var"
#in middleware:
async def my_middlware(request):
    result = do_processiong()
    request.headers[MY_MIDDLEWARE_VAR] = result

#in route handler
async def index(request):
    middlware_result = request.headers.pop(MY_MIDDLEWARE_VAR)
    ...
```

**Comment by eisneim** [comment] 2017-10-16 01:46
@ashleysommer thanks, i actually did the same, but instead, the key name i use is `hashed`  in order to improve security level

**Comment by ashleysommer** [comment] 2017-10-17 03:38
As this was a question, not a bug report or feature request, if you believe your question has been adequately answered, can you please close this issue.

Go ahead and open an issue for a feature request if you'd like to see a request context added, however that might be better implemented using a plugin.

**Closed** 2017-10-18 06:07 UTC
