### ISSUE TITLE
Sanic Documentation

### ISSUE THREAD

**Issue by sinahmr** [channelcat/sanic#552] opened 2017-03-13 08:36 UTC
I'm going to use Sanic 0.4 (or maybe 0.5 in few days), but it seems the documentation [here](http://sanic.readthedocs.io/en/latest/index.html) is out of date.
Am I right? Won't you update documents in readthedocs?
Thanks.

**Comment by qwexvf** [comment] 2017-03-13 17:12
maybe there's a few things outdated, but you can do almost everything the same.

at least what i can confirm is that listeners are not working for me...

**Comment by messense** [comment] 2017-03-14 01:45
The documentation on ReadTheDocs is apparently out of date, the title says `Sanic 0.31 documentation` while the latest version is `0.4.1`.

Something is wrong with ReadTheDocs build I think.

**Comment by r0fls** [comment] 2017-03-15 06:24
@channelcat @seemethere @kdelwat I can't even log into my http://readthedocs.io account (apparently I have two and can't reset the one with access to Github). If any of you can look into why the build is breaking that would be awesome.

**Comment by sinahmr** [comment] 2017-03-15 07:38
@messense 
So can you help me to build it myself?
When I write "make html" command in my sanic/docs directory, I get the following error:
`Running Sphinx v1.3.6
Exception occurred:
  File "conf.py", line 14, in <module>
    from recommonmark.parser import CommonMarkParser
ImportError: No module named recommonmark.parser
The full traceback has been saved in /tmp/sphinx-err-M6Tal3.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 1`
(recommonmark itself is installed in my system)

**Comment by messense** [comment] 2017-03-15 07:39
@sinahmr `pip install -r requirements-dev.txt`

**Comment by sinahmr** [comment] 2017-03-15 07:46
@messense Tnx

**Comment by kdelwat** [comment] 2017-03-15 08:12
@r0fls I will look into the issue in the next day or too.

**Comment by messense** [comment] 2017-03-16 14:21
After #561 merged ReadTheDocs build still seems broken.
Would you guys consider uploading documentation to  http://pythonhosted.org/ for now?

**Comment by seemethere** [comment] 2017-03-16 18:42
Doesn't appear to be broken, I think it just generates docs on a release.

**Comment by seemethere** [comment] 2017-03-16 18:43
Just manually triggered a build and it seems to be working fine when I trigger it manually.

**Comment by kdelwat** [comment] 2017-03-16 20:00
@messence @seemethere On my test ReadTheDocs account it definitely now works fine. Could be a problem with the Git hook?

**Comment by seemethere** [comment] 2017-03-16 20:10
@kdelwat I'd believe so but I don't have admin access to the repo so it could be difficult to discern.

@channelcat to the rescue?

**Comment by r0fls** [comment] 2017-03-17 02:26
This looks to be working fine now. Anyone feel free to reopen if there is still an issue.

**Closed by r0fls** 2017-03-17 02:26 UTC
