### ISSUE TITLE
RouteExists should account url_prefixing

### ISSUE THREAD

**Issue by acdha** [channelcat/sanic#1300] opened 2018-08-28 17:32 UTC
This currently returns an error. It's possible to work around it but it seems like it should work as long as the url prefix doesn't produce a conflict:

```
app = Sanic()
bp = Blueprint("test", url_prefix="/test")
app.blueprint(bp, url_prefix="/test")

@bp.route("/")
def index(request):
    return text("Hello World")

@app.route("/")
def health_check(request):
    return text("OK")
```

**Comment by r0fls** [comment] 2018-08-28 20:30
The issue is likely that you can't register the blueprint before defining the routes:


```
from sanic.app import Sanic
from sanic.response import text
from sanic.blueprints import Blueprint

app = Sanic()
bp = Blueprint("test", url_prefix="/test")


@bp.route("/")
def index(request):
    return text("Hello World")

@app.route("/")
def health_check(request):
    return text("OK")

if __name__  == "__main__":
    app.blueprint(bp)
    app.run()
```


This works fine, at least on the master branch:

```
$ curl localhost:8000/test/
Hello World
$ curl localhost:8000/
OK
```

Going to close this issue but feel free to reopen if you still have problems.

**Closed by r0fls** 2018-08-28 20:30 UTC
