### ISSUE TITLE
Blueprints don't work when running sanic with asynchronous support

### ISSUE THREAD

**Issue by xNyo** [channelcat/sanic#945] opened 2017-09-16 18:00 UTC
I can't manage to execute blueprints when sanic runs with [asynchronous support](https://github.com/channelcat/sanic/blob/master/docs/sanic/deploying.md#asynchronous-support).   

**Example code:**
```
import asyncio
from sanic import Blueprint, Sanic

bp = Blueprint("test")


@bp.listener("before_server_start")
async def before_server_start(app, loop):
    print("before_server_start")


@bp.listener("before_server_stop")
async def before_server_start(app, loop):
    print("after_server_start")

if __name__ == "__main__":
    app = Sanic()
    app.blueprint(bp)

    server = app.create_server(host="0.0.0.0", port=1337)
    loop = asyncio.get_event_loop()
    task = asyncio.ensure_future(server)
    try:
        loop.run_forever()
    except:
        loop.close()

    # app.run(host="0.0.0.0", port=1337)

```

**Output with `app.run()`**
```
2017-09-16 19:52:02 - (sanic)[INFO]: Goin' Fast @ http://0.0.0.0:1337
before_server_start
2017-09-16 19:52:02 - (sanic)[INFO]: Starting worker [3143]
^C2017-09-16 19:52:05 - (sanic)[INFO]: Stopping worker [3143]
after_server_start
2017-09-16 19:52:05 - (sanic)[INFO]: Server Stopped
```

**Output with `ensure_future()`**
```
2017-09-16 19:53:29 - (sanic)[INFO]: Goin' Fast @ http://0.0.0.0:1337
^C
```

As you can see, the two blueprints are run only when using `app.run()`, is there an issue with my code or are blueprints just not supported when using `asyncio.ensure_future()`?

**Comment by jrocketfingers** [comment] 2017-09-16 19:25
Try adding a route, you'll find out that blueprints do work :) But on the topic of listeners not being called: the issue is that if you run Sanic async it returns the serving coroutine before triggering `before_start` events.

If Sanic returns you a coroutine instead of launching it on it's own, we can't really know when it will be done.

The lines in question: https://github.com/channelcat/sanic/blob/master/sanic/server.py#L505-L508

@r0fls is this a known and expected behavior? E.g. should triggering events not be done if `run_async` is set? Imo, yes, since we're relinquishing control there by given consent.

**Comment by xNyo** [comment] 2017-09-16 21:45
Makes sense, thanks for the help! I use the listeners to initialize and close connections to the database and stuff like that, so I'll just call the initialize/dispose coroutines before starting the loop and before stopping it, like so:
```
try:
    loop.run_until_complete(before_server_start(app, loop))
    loop.run_forever()
finally:
    loop.run_until_complete(before_server_stop(app, loop))
    loop.close()
```

**Comment by jrocketfingers** [comment] 2017-09-20 13:41
Hey, not to bother, but could you close the issue?

**Closed** 2017-09-20 17:58 UTC
