### ISSUE TITLE
Publish documentation

### ISSUE THREAD

**Issue by wilcoschoneveld** [channelcat/sanic#321] opened 2017-01-20 09:12 UTC
e.g. with Sphinx integrated it should be possible to import the repository at https://readthedocs.org/.

@seemethere can you facilitate this?

**Comment by wilcoschoneveld** [comment] 2017-01-20 09:12
@kdelwat fyi

**Comment by kdelwat** [comment] 2017-01-20 09:16
The problem is that Read the Docs doesn't support Python 3.5 syntax natively yet, as discussed [here](https://github.com/rtfd/readthedocs.org/issues/1990). There seems to be a workaround using Conda in that thread which would be a good solution.

**Comment by zkanda** [comment] 2017-01-20 09:40
If you look on that issue, this seems to be it: http://stackoverflow.com/a/36144269

I can send a PR if using conda is an accepted solution here.

**Comment by wilcoschoneveld** [comment] 2017-01-20 12:49
IMO conda is a good solution.

**Comment by seemethere** [comment] 2017-01-27 01:51
This could be a possibility in the future but I don't see the added benefit just yet. The on-github docs done by @kdelwat seem to work great and if there's not a reason to add complexity then we shouldn't.

**Comment by luizberti** [comment] 2017-01-30 08:41
I would say migrating docs into GitHub's built in Wiki feature and allowing for community edits would be a great way to improve the currently bare-boned docs right now.

Not to mention it takes away much of the overhead from contributing documentation, not having to fork, clone, edit, push, PR, merge or anything.

Plus it's nice having doc contributions separate from actual code contributions, it declutters the PR interface, and is overall less stuff to micro-manage.

**Comment by JordanP** [comment] 2017-01-30 10:02
> it's also nice having doc contributions separate from actual code contributions.
Nope. Good practice is too treat doc as code, and have it in the same repo. 

>fork, clone, edit, push, PR, merge or anything
People are very used to this workflow.

Also being not too tied with Github might be a good idea.

**Comment by luizberti** [comment] 2017-01-30 12:36
It would not be tied to GitHub at all, it's still a Git repository that will live under `github.com/channelcat/sanic.wiki.git`, except it will appear integrated into this repo under the _Wiki_ tab.

You can still clone it and move it wherever you want, it's just a git versioned folder of Markdown files (much like what `docs` currently is) except it has navigation controls and a nice Web editing interface that lets you contribute docs without forking the whole thing and dealing with the bureaucracy of PRs which might be routine stuff for many, but I still believe it's burdensome to most.

It would be a relatively painless thing to implement and try out, and it might lead to more contributions given that it lowers the barrier of effort needed to submit improvements. Might be worth testing out, all it takes is mirroring the Markdown documents from the `docs` folder into the Wiki and seeing how it goes...

**Comment by zkanda** [comment] 2017-01-31 03:05
I think this can be closed: https://sanic.readthedocs.io/en/latest/

@luizberti maybe open a different issue for that?

**Comment by seemethere** [comment] 2017-01-31 03:54
I'd agree. I like the wiki style for some things but I think the docs should stay checked in with the code.

Maybe we can agree for some of the docs to go to the wiki (like extensions).

But @zkanda is right I'll close this issue.

@luizberti feel free to open a different issue regarding moving the docs to a github wiki.

**Closed by seemethere** 2017-01-31 03:54 UTC
