### ISSUE TITLE
strict slashes false positive for subsequent blueprint registrations

### ISSUE THREAD

**Issue by jamesstidard** [channelcat/sanic#1014] opened 2017-11-11 11:33 UTC
Ran into a configuration which doesn't correctly honour the `strict_slashes` setting. I did have a look at trying to commit a fix myself but wasn't able to. The relevant statement is [here](https://github.com/channelcat/sanic/blob/master/sanic/router.py#L143). Happens due to `self.routes_all.get(uri[:-1], False)`, so switching the registration order of `get` and `post` below will cause `$ http get localhost:8000/bp` to throw the error.

Example:

```python
from sanic import Blueprint, Sanic
from sanic.response import text


bp = Blueprint('bp', url_prefix='bp')

@bp.get('/')
def get(_):
    return text('get got')

@bp.post('/')
def post(_):
    return text('post got')


def main():
    app = Sanic(__name__)
    app.blueprint(bp)
    app.run(host="0.0.0.0", port=8000, workers=4)


if __name__ == '__main__':
    main()
```

```fish
$ http get localhost:8000/bp/
$ http get localhost:8000/bp
$ http post localhost:8000/bp/
$ http post localhost:8000/bp  # Method POST not allowed
```

**Comment by yunstanford** [comment] 2018-01-28 01:18
Can't reproduce this anymore.

**Comment by r0fls** [comment] 2018-01-28 01:39
@jamesstidard closing this, feel free to reopen if needed.

**Closed by r0fls** 2018-01-28 01:39 UTC
